export DOCKER_CLI_EXPERIMENTAL="enabled"
export NVM_NODEJS_ORG_MIRROR="https://npm.taobao.org/mirrors/node"
export YARN_REGISTRY="https://registry.npm.taobao.org"
export ELECTRON_MIRROR="https://npm.taobao.org/mirrors/electron/"
export ELECTRON_BUILDER_BINARIES_MIRROR="https://npm.taobao.org/mirrors/electron-builder-binaries/"
export SASS_BINARY_SITE="https://npm.taobao.org/mirrors/node-sass"
export PATH="$(yarn global bin):${PATH}"
